[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.34"

[features]
seeds = false
skip-lint = false

[programs.localnet]
raydium_cp_swap = "HEW7NWmUzsYNfNdJRTMaM3RaEFX8JDfdLwDWydkxBAXS"

[registry]
url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
cluster = "https://staging-rpc.dev2.eclipsenetwork.xyz"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/cp-swap"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.test.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://staging-rpc.dev2.eclipsenetwork.xyz"
# rpc_port = 1337                                 # Set JSON RPC on this port, and the next port for the RPC websocket.
# gossip_port = 1337                              # Gossip port number for the validator.
# faucet_port = 1337                              # Enable the faucet on this port.

[[test.validator.clone]]
address = "Bzsi8fW9x4ahRgC8xNdxrr5NNWm8DBSrQnE322vi1YWH"

[[test.validator.clone]]
address = "F8vHGYNxWoLWrLYJ6HrksGH7V8TQeqZJPeGNiYkfdYhN"
